spring:
  datasource:
    username: goia-catalin
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_licenta
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8082